{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ include "observability-demo.namespace" . }}
  labels:
    {{- include "observability-demo.labels" . | nindent 4 }}
    {{- include "observability-demo.frontendLabels" . | nindent 4 }}
    app: observability-demo
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "observability-demo.frontendLabels" . | nindent 4 }}
    app: observability-demo
{{- end }}
